#!/bin/sh

set -eu
realqemu=$(basename "${0}")
realqemu=${realqemu%%-swtpm}
if [ "${realqemu}" = qemu ]; then
    realqemu="qemu-system-$(uname -m)"
fi

uid=$(id -u)
HOME=${HOME:=/tmp/${uid}}
XDG_DATA_HOME=${XDG_DATA_HOME:-${HOME}/.local/share}
TPM_DATA_DIR=${XDG_DATA_HOME}/qemu-swtpm
tpmkey=$(echo "$(pwd)" "$@" | sha1sum | awk '{print($1)}')
tpmdir="${TPM_DATA_DIR}/${tpmkey}"
mkdir -p "${TPM_DATA_DIR}"
if [ ! -d "${tpmdir}" ]; then
    mkdir -p "${tpmdir}"
    swtpm_setup \
        --tpmstate dir://${tpmdir} \
        --tpm2 \
        --pcr-banks sha256
fi

swtpm socket \
    --tpmstate dir=${tpmdir} \
    --ctrl type=unixio,path=${tpmdir}/swtpm-sock \
    --log level=0 \
    --tpm2 \
    --terminate \
    --daemon

echo "qemu-swtpm starting ..."
echo "qemu binary: ${realqemu}"
echo "qemu args: " "$@"
echo "tpm state: ${tpmdir}"
echo

tpmdevice=tpm-tis
case "${realqemu}" in
    qemu-system-aarch64|qemu-system-arm)
        tpmdevice=tpm-tis-device
        ;;
esac

exec "${realqemu}"  \
    "$@" \
    -chardev socket,id=chrtpm,path=${tpmdir}/swtpm-sock \
    -tpmdev emulator,id=tpm0,chardev=chrtpm \
    -device $tpmdevice,tpmdev=tpm0
