#!/bin/bash

ME=$0
ME_FULL=$(readlink -f $0)
MY_DIR=$(dirname $ME_FULL)
BASE_DIR=$(dirname $MY_DIR)
MY_NAME=$(basename $ME)
REAL_UTIL=${MY_NAME#my-}

case $1 in
--install)
    echo "install to user's .ssh dir"
    echo "not yet"
    exit 2
#    if [ -r ~/.ssh/config ]; 
    ;;
esac

#echo "$0" "$@"

if [ $PWD != $BASE_DIR -a $REAL_UTIL = "scp" ]; then
    echo "error: my-scp only works from the base directory"
    echo "  BASE_DIR=$BASE_DIR"
    echo "  PWD=$PWD"
    exit 2
fi

# just do this every time in case the dir moves
cat >$BASE_DIR/ssh/config <<EOF
Include $BASE_DIR/ssh/config.d/*
Include ~/.ssh/config
EOF

# this is needed on a fresh git clone
chmod go-rwx $BASE_DIR/ssh/dummy-key*

cd $BASE_DIR
$REAL_UTIL -F ./ssh/config "$@"
