#!/bin/bash

# Boot a qemu machine and runs tests on it
# use tmux to visualize status while running
# record the results in test logs
# handle test OK, FAIL, TIMEOUT, and HANG
# handle boot failures (of target software or qemu itself)
#
# For RUNS
#    For each TESTS
#       Boot QEMU and wait for ready
#       For TRYS
#           run test on target while watching status from host
#           record status
#           if ! recoverable failure
#                break
#        if ! hung
#           attempt to shutdown qemu gracefully
#        else
#           kill qemu
#

#set -x

ME=$(readlink -f $0)
MY_NAME=$(basename $ME)
MY_DIR=$(dirname $ME)
export BASE_DIR=$(dirname $MY_DIR)
export IMAGES=$BASE_DIR/images

LOGS=$BASE_DIR/logs
mkdir -p $LOGS
PID_FILE=$LOGS/qemu.pid

: ${NOW:=$(date +%Y-%m-%d-%H%M%S)}
export NOW
LOG=$LOGS/$NOW-test-log.log
TOTALS=$LOGS/$NOW-totals.txt

TMP_MARKER=test-qemu-marker

RUNS=2
TRYS=2

BOOT_WAIT=30
SHUTDOWN_WAIT=30
KILL_WAIT=10

TEST_WAIT=60
SSH_FAIL_COUNT=5
TRY_CONTINUE=true

TESTS=( dummy )

FILTER_TOTALS=true

QEMU_SSH_NAME=qemu
QEMU_BOOT_SCRIPT="scripts/qemu-run"
QEMU_BOOT_ARG="xen"
SESSION_NAME=test-qemu

error() {
    echo "$@"
    exit 2
}

tmux-panel-title() {
    printf '\033]2;%s\033\\' "$1"
}

format_msg() {
    MSG1=$(printf "%-8s %4d %-8s %s" $1 $2 $3 $4)
    shift 4
    echo "$MSG1 $@"
}

update_totals() {
    echo "TOTAL=$TOTAL FAIL=$FAIL" >$TOTALS.new
    echo "LAST $LAST_OK" >>$TOTALS.new
    if $FILTER_TOTALS; then
        tac $LOG | grep -v "^OK " | grep -v "^#" | head -n 25 >>$TOTALS.new
    else
        echo "LAST $LAST_FAIL" >>$TOTALS.new
        tac $LOG | grep -v "^#" | head -n 25 >>$TOTALS.new
    fi
    mv -f $TOTALS.new $TOTALS
}

init_totals() {
    LAST_OK=$(printf "%-8s %s" OK none)
    LAST_FAIL=$(printf "%-8s %s" FAIL none)
    TOTAL=0
    FAIL=0
    update_totals
}


record_success() {
    TOTAL=$(( $TOTAL + 1 ))
    MSG=$(format_msg "$@")
    echo "$MSG"
    echo "$MSG" >>$LOG
    LAST_OK="$MSG"
    update_totals
}

record_failure() {
    TOTAL=$(( $TOTAL + 1 ))
    FAIL=$(( $FAIL + 1 ))
    MSG=$(format_msg "$@")
    echo "$MSG"
    echo "$MSG" >>$LOG
    LAST_FAIL="$MSG"
    update_totals
}

start_timer() {
    START=$(date +%s)
}

get_timer() {
    END=$(date +%s)
    echo $(( $END - $START ))
}

wait_for_ssh() {
    start_timer
    echo -n "waiting for ssh "
    for i in $(seq 1 $BOOT_WAIT); do
        if ssh -o ConnectTimeout=2 $QEMU_SSH_NAME true >/dev/null 2>&1; then
            DELAY=$(get_timer)
            echo " OK"
            return
        fi
        echo -n "."
        sleep 1
    done
    DELAY=$(get_timer)
    echo " NOBOOT"
    false
}

###### Remote test support

# we are on the host, perform a subcmd on the target
remote_action() {
    scp -q $ME $QEMU_SSH_NAME:
    ssh $QEMU_SSH_NAME chmod +x ./$MY_NAME
    ssh $QEMU_SSH_NAME ./$MY_NAME subcmd "$@"
}

# we are on the target, start an detached action
# (The actual deferral delay is in the action function)
do_defer_start() {
    case $1 in
    defer_test_run)
        #echo "deferred $2 $3 $4 $5 $6 $7 $8 $9"
        true
        ;;
    defer_shutdown)
        #echo "deferred shutdown $2 $3 $4 $5 $6 $7 $8 $9"
        true
        ;;
    *)
        echo "start $@"
        ;;
    esac
    rm -rf test-result.*
    echo "$ME subcmd $@" | at now + 0 minute  >test-result.start 2>&1
}

# we are on the target, this is the action for a deferred test run
do_defer_test_run() {
    TEST=$1; shift
    set -o pipefail

    exec >/dev/console 2>&1 </dev/null
    if [ ! -r ${TEST}-test.sh ]; then
        error "${TEST}-test.sh does not exist!"
    else
        chmod +x ${TEST}-test.sh
    fi
    echo "sleeping 2 seconds to allow ssh to exit"
    sleep 2
    echo "starting test $TEST"
    ./${TEST}-test.sh run "$@" | tee test-result.log
    echo $? >test-result.done
}

# we are on the host
# use ssh to check on the target and see if the deferred test is done
#
# returns 0 for test completed with 0 exit status
# returns !0 for anything else
# always sets global var CAUSE
check_ssh() {
    local time=$1
    local timeout=$2
    local fails=0

    echo -n "checking ssh "
    start_timer
    for i in $(seq 1 $1); do
        if scp -o ConnectTimeout=2 \
            -o ServerAliveInterval=2 \
            -o ServerAliveCountMax=2 \
            $QEMU_SSH_NAME:test-result.* $LOGS/. >/dev/null 2>&1; then
            echo -n "."
            FAILS=0
            if [ -r $LOGS/test-result.done ]; then
                DELAY=$(get_timer)
                # allow the at job to finish and remove itself from the atq
                sleep 1

                if [ x"$(cat $LOGS/test-result.done)" = x"0" ]; then
                    CAUSE="OK"
                    echo " $CAUSE"
                    return 0
                else
                    CAUSE="FAIL"
                    echo " $CAUSE"
                    return 1
                fi
            fi
        else
            echo -n "!"
            FAILS=$(( $FAILS + 1 ))
            if [ $FAILS -gt $timeout ]; then
                DELAY=$(get_timer)
                CAUSE="HANG"
                echo " $CAUSE"
                return 1
            fi
        fi
        sleep 1
    done
    DELAY=$(get_timer)
    CAUSE="TIMEOUT"
    echo " $CAUSE"
    return 1
}

sync_files() {
    REMOTE_FILES=""
    OK=true
    for f in $@; do
        if [ -r $f ]; then
            f_n=$(basename $f)
            REMOTE_FILES="$REMOTE_FILES $f_n"
        else
            echo "file not found: $f"
            OK=false
        fi
    done

    # we don't want to exit on the first missing file, find all of them
    # but now that we know there is at least one return error
    if ! $OK; then
        return 1
    fi

    ssh $QEMU_SSH_NAME stat -c "'%f %s %Y %n'" $REMOTE_FILES >$LOGS/remote-stats
    for f in $@; do
        f_n=$(basename $f)
        f_d=$(dirname $f)
        LOCAL_FILE_STAT=$(cd $f_d; stat -c '%f %s %Y %n' $f_n)
        if ! grep -q "$LOCAL_FILE_STAT" $LOGS/remote-stats; then
            scp -p $f $QEMU_SSH_NAME:
        fi
    done
}

# perform a test on the target in a deferred way
# the test itself will be a separate file
#
# we use deferred tests for anything that may cause the target
# (or the emulator) to hang
#
# returns 0 for test completed with 0 exit status
# returns !0 for anything else
# always sets global var CAUSE
do_one_deferred_test() {
    echo "test $1"
    if [ ! -x $1-test.sh ]; then
        echo "$1-test.sh does not exist or is not -x"
        CAUSE="NOFILE"
        DELAY=0
        return 1
    fi
    FILES="$(./$1-test.sh files)"
    if [ -n "$FILES" ]; then
        if ! sync_files $FILES; then
            CAUSE="NOFILE"
            DELAY=0
            return 1
        fi
    fi
    rm -rf $LOGS/test-result.*
    scp -q $1-test.sh $QEMU_SSH_NAME:
    remote_action defer_start defer_test_run "$@"
    check_ssh $TEST_WAIT $SSH_FAIL_COUNT
}

do_one_quick_test() {
    echo "ssh command"
    ssh $QEMU_SSH_NAME true
}

do_one_test() {
    do_one_deferred_test $@
}

###### Shutdown support
qemu_running() {
    if [ -r $PID_FILE ]; then
        ps --pid $(cat $PID_FILE) >/dev/null
    else
        false
    fi
}

wait_qemu_stop() {
    echo -n "waiting for qemu to stop "
    start_timer
    for i in $(seq 1 $SHUTDOWN_WAIT); do
        if ! qemu_running; then
            DELAY=$(get_timer)
            echo " OK"
            return
        fi
        echo -n "."
        sleep 1
    done
    DELAY=$(get_timer)
    echo " TIMEOUT"
    false
}

do_defer_shutdown() {
    exec >/dev/console 2>&1 </dev/null
    echo "sleeping 2 seconds to allow ssh to exit"
    sleep 2
    echo "starting shutdown"
    shutdown now
}

do_shutdown() {
    remote_action defer_start defer_shutdown
    wait_qemu_stop
}

kill_qemu() {
    if [ -r $PID_FILE ]; then
        PID=$(cat $PID_FILE)
    else
        return
    fi

    for i in $(seq 1 $KILL_WAIT); do
        if qemu_running; then
            kill -3 $PID
            sleep 1
        else
            return 0
        fi
    done
    false
}

###### Windows and main
do_totals() {
    tmux-panel-title "totals"
    watch -t -n 1 -d cat $TOTALS
}

clean_tmp() {
    MY_TMPDIR=$(dirname $TMPDIR)
    if [ -e $MY_TMPDIR/test-qemu-tmp/$TMP_MARKER ]; then
        echo "cleaning our private tmp dir"
        rm -rf $MY_TMPDIR/test-qemu-tmp/* || true
        touch $MY_TMPDIR/test-qemu-tmp/$TMP_MARKER || error "Can't touch tmp marker"
    else
        echo "private tmp dir not found"
    fi
}

do_host() {
    tmux-panel-title "host side $@"
    init_totals
    echo "# LOG=$LOG"
    echo "# RUNS=$RUNS TRYS=$TRYS TESTS=${TESTS[@]}" | tee -a $LOG
    echo "#"                                    >>$LOG
    echo "# QEMU_DIR=$QEMU_DIR"                 >>$LOG
    echo "# QEMU_BOOT_SCRIPT=$QEMU_BOOT_SCRIPT" >>$LOG
    echo "# QEMU_BOOT_ARG=$QEMU_BOOT_ARG"       >>$LOG
    echo "# KERNEL_VER=$KERNEL_VER"             >>$LOG
    echo "#"                                    >>$LOG
    echo "# BOOT_WAIT=$BOOT_WAIT"               >>$LOG
    echo "# SHUTDOWN_WAIT=$SHUTDOWN_WAIT"       >>$LOG
    echo "# TEST_WAIT=$TEST_WAIT"               >>$LOG
    echo "# TRY_CONTINUE=$TRY_CONTINUE"         >>$LOG

    for run in $(seq 1 $RUNS); do
        for t in ${TESTS[@]}; do
            tmux-panel-title "run=$run test=$t boot"
            tmux split-window -h "$ME subcmd qemu $t"
            if wait_for_ssh $BOOT_WAIT; then
                record_success OK $run BOOT 0 "($DELAY Sec)"
                status=true
                try_shutdown=true
                for try in $(seq 1 $TRYS); do
                    tmux-panel-title "run=$run test=$t try=$try"
                    if ! do_one_test $t; then
                        record_failure $CAUSE $run $t $try "($DELAY Sec)"
                        status=false
                        if [ x"$CAUSE" = x"HANG" ]; then
                            # if ssh is not working don't try shutdown
                            try_shutdown=false
                            break
                        elif [ x"$CAUSE" = x"TIMEOUT" ]; then
                            # for timeout we can't go on but we can try shutdown
                            break
                        elif ! $TRY_CONTINUE; then
                            # for fail we can go on if we want to
                            break
                        fi
                    else
                        record_success OK $run $t $try "($DELAY Sec)"
                    fi
                done
                if $try_shutdown; then
                    echo "graceful shutdown of qemu"
                    if do_shutdown; then
                        record_success OK      $run SHUTDOWN 0 "($DELAY Sec)"
                    else
                        record_failure TIMEOUT $run SHUTDOWN 0 "($DELAY Sec)"
                        kill_qemu
                    fi
                else
                    echo "forcefully terminate qemu"
                    kill_qemu
                fi
            else
                record_failure NOBOOT $run BOOT 0 "($DELAY Sec)"
                kill_qemu
            fi
            sleep 1
            clean_tmp
            sleep 1
        done
    done
    tmux kill-win
}

# This is the tmux window pane function to actually run qemu
do_qemu() {
    tmux-panel-title "$QEMU_BOOT_SCRIPT $QEMU_BOOT_ARG $@"
    QEMU_TMUX=no $BASE_DIR/$QEMU_BOOT_SCRIPT $QEMU_BOOT_ARG "$@"
}

mk_env() {
cat >$ENV_FILE <<EOF
RUNS="$RUNS"
TRYS="$TRYS"
BOOT_WAIT="$BOOT_WAIT"
SHUTDOWN_WAIT="$SHUTDOWN_WAIT"
KILL_WAIT="$KILL_WAIT"
TEST_WAIT="$TEST_WAIT"
SSH_FAIL_COUNT="$SSH_FAIL_COUNT"
TRY_CONTINUE="$TRY_CONTINUE"
FILTER_TOTALS="$FILTER_TOTALS"
QEMU_SSH_NAME="$QEMU_SSH_NAME"
QEMU_BOOT_SCRIPT="$QEMU_BOOT_SCRIPT"
QEMU_BOOT_ARG="$QEMU_BOOT_ARG"
SESSION_NAME="$SESSION_NAME"

TESTS=( ${TESTS[@]} )
EOF
}

# main starts things up and then waits for tmux to finish or detach
main() {
    if [ -n "$TMUX" ]; then
        echo "nested tmux not supported"
        exit 2
    fi

    if [ -z "$1" -o ! -d $1 ]; then
        error -e "The first argument to test-qemu should be a directory, like:\n" \
        "./scripts/test-qemu tests/dummy"
    else
        cd $1; shift
    fi

    if [ -e ./test-qemu-vars ]; then
        . ./test-qemu-vars
        export TEST_QEMU_VARS=$PWD/test-qemu-vars
    fi

    while [ -n "$1" ]; do
        ARG="$1"; shift
        echo "ARG=$ARG"
        case "$ARG" in
        only)
            TESTS=( )
            ;;
        once)
            export RUNS=1; export TRYS=1
            ;;
        *)
            if [ -r $ARG-test.sh ]; then
                TESTS+=( $ARG )
            elif [ -r $ARG -a "$ARG" != "${ARG%-test.sh}" ]; then
                TESTS+=( ${ARG%-test.sh} )
            else
                echo "Don't know what to do with $ARG"
            fi
            ;;
        esac
    done

    export ENV_FILE=$LOGS/this-session-qemu-vars
    mk_env
    export TEST_QEMU_VARS=$ENV_FILE

    : ${TMPDIR:=/tmp}
    export MY_TMPDIR=$(mktemp -d -p $TMPDIR test-qemu-XXXXXXXX)
    mkdir -p $MY_TMPDIR/test-qemu-tmp || error "Can't create tmp dir"
    if ! touch $MY_TMPDIR/test-qemu-tmp/$TMP_MARKER; then
        error "Can't create private tmpdir"
    fi
    export TMPDIR=$MY_TMPDIR/test-qemu-tmp

    touch $LOG
    echo "Starting..." >$TOTALS

    tmux start-server
    tmux new-session -d -s QEMU -n $QEMU_WIN_NAME -d "$ME subcmd totals"
    SESS="QEMU"
    tmux set -s -t $SESS mouse on

    tmux set -w -t $SESS:$QEMU_WIN_NAME pane-border-status top

    # the host pane is the driver of it all
    # create it and let it create and destroy the qemu pane
    tmux split-window -v -l $(( $LINES - 10 )) -t $SESS:$QEMU_WIN_NAME "$ME subcmd host"

    #sleep 1
    #tmux select-pane -t $SESS:$QEMU_WIN_NAME.1

    tmux attach -t$SESS:$QEMU_WIN_NAME

    # if finished or killed (but not detached)
    if ! tmux has -t$SESS >/dev/null 2>&1; then
        clean_tmp
        echo "LOG=$LOG"
        cat $TOTALS
    fi
}

if [ -n "$TEST_QEMU_VARS" ]; then
    . $TEST_QEMU_VARS
fi

if [ x"$1" = x"subcmd" ]; then
    CMD=$2
    shift; shift;
    do_$CMD "$@"
elif [ x"$1" = x"help" ]; then
    echo "this runs a sequence of tests using qemu"
    echo "look at test-qemu-vars for examples"
    exit 2
else
    main "$@"
fi